### ISSUE TITLE
"Error: Timeout after 5 seconds while waiting for data from Comfoair"

### ISSUE THREAD

**Issue by L1brTy** [coolchip/node-red-contrib-comfoair#1]
Hi, 

I trigger the "getTemperatureStates" every ten minutes to write the data in my InfluxDB.

after a while, I get timeouts from the node. To fix it,  restart of the Comfoair works, restart of nodered not.

I noticed that it happens faster if I reduce the polling intervall to e.g 5 minutes.

Do you have similar experiences or should I test a different usb / rs232 converter ?

The line is < 10m and i dont expect noise on it.

My second finding is, that sometimes the temperatures are not converted correctly (see attached screenshot). 

Same question here.

![Zehnder](https://user-images.githubusercontent.com/57085514/67656359-def96980-f953-11e9-903e-90b360e34506.PNG)

Anyway: Great thanks for this nice node :)

Best regards

**Comment by coolchip** [comment]
Unfortunately I also get this timeouts. I'm quiet shure that this is a false implementation of the escape sequences of the comfoair protocol.
If I get some time again, I'll take care of it.

**Comment by coolchip** [comment]
What do you mean with "sometimes temperatures are not converter correctly"?

**Comment by coolchip** [comment]
I reviewed the code of the basic packet node-comfoair and found a view issues. Because of this issues you get wrong values sometimes. Now I will bring this changes to the node red node.

**Comment by beireken** [comment]
I have the same problem. Before I used the serial node to send basic commands ( like "07 f0 00 d1 00 7e 07 0f" for requesting temperatures) to the comfod, this never failed but was a bit ghetto :) 

I really your node though!

**Comment by t0mkdev** [comment]
I'm having the same timeout issue after a few calls. I then need to redeploy my flows and it works for a few calls again.. Any idea? 

Could it be that we should disable the CC Ease, since they interfere with each other on RS232? I've read about it in multiple places. Here is an "active" switch people have implemented: https://www.openhab.org/addons/bindings/comfoair1/#list-of-commands

EDIT: I can confirm that after disconnecting the CC Ease everything works flawlessly.

**Comment by beireken** [comment]
I have nothing else connected, and still have the problem, so it's not only related to cc ease.

**Comment by coolchip** [comment]
I've done a complete rewrite of the code. Some things are working better now but unfortunately there are still those timeouts. In general there is no problem if a timeout accours from time to time. But the problem for me is, that I have to restart node-red if it's throwing this error. I will search for it next time...

**Comment by beireken** [comment]
I updated yesterday evening. (Your node and node-red) Up until now it is still working! I have a 10second interval on the requests, before it was only working for a couple of hours.
So definitely an improvement. I'll update here if it does timeout again!

**Comment by coolchip** [comment]
Thanks for your positive reply. I also use it since a while. For me its also working much better. But unfortunately I get timeouts sometime. 
The problem for me isn't the timeout but the whole node hangs up if only one timeout occurred. I will search for it.

**Comment by beireken** [comment]
Small update. Still working since my update 12 days ago!

I am seeing some wrong received values from time to time. As seen in this graph from one of the fan speeds.
![comfo](https://user-images.githubusercontent.com/5359577/71561306-10d29d80-2a75-11ea-8757-f68c17c145a4.png)

**Comment by mifrey00** [comment]
I updated the node to version 0.0.5 but I have this timeout issue almost all the time.

I verified that the exchanged data are correct.  Below, I used jpnevulator to sniff the data.  It creates a virtual port (used by the comfoair node) and passes all the data from and to ttyUSB1 (connected to the ventilation unit).  We can see the ventilation unit responds to the request right away but I get the error _"comfoair [/dev/pts/0] runCommand(getTemperatures): Command "getTemperatures" timeout exceeded"_ in node-RED.

![image](https://user-images.githubusercontent.com/10077480/98710817-732e4700-2384-11eb-8dca-6ddaa134e1cd.png)

**Comment by coolchip** [comment]
Thank you for that detailed trace. Hope I can find somethink. I think its somethink with the crc calculation or the escape sequence with 0x07.

**Comment by mifrey00** [comment]
Just tried with the v0.0.6 but still have exactly the same behavior:  jpnevulator shows correct sent and received data but but the node timeouts.  Is there any "quick and dirty" workaround?

**Comment by coolchip** [comment]
I've release v0.0.7. I've fixed a bug in the error handler. Should be much more stable now.
