### ISSUE TITLE
[Feature Request] Add Command "Set RS232 Mode" 

### ISSUE THREAD

**Issue by Element115sw** [coolchip/node-red-contrib-comfoair#16]
Hi could you please add Command 0x9B as seen in the picture. It would really help me. Thank you!

![setRS232](https://user-images.githubusercontent.com/63460813/119656811-68706680-be2b-11eb-9435-190ccec16ce6.png)

**Comment by coolchip** [comment]
Its possible but it has to been done in the underlying module https://github.com/coolchip/node-comfoair. Perhaps you want to give me a pull request?

**Comment by coolchip** [comment]
If this is still an issue, please open a new issue at  https://github.com/coolchip/node-comfoair and describe why you need this.
