### ISSUE TITLE
supply exhaust outgoing outside

### ISSUE THREAD

**Issue by VincentSC** [coolchip/node-red-contrib-comfoair#17]
Zehnder talks about intake, exhaust, supply and extract. Or extract, supply, incoming and outgoing.

This library uses supply, exhaust, outgoing and outside.

![intake-exhaust-supply-extract](https://user-images.githubusercontent.com/5090382/120239403-7fb1b880-c25e-11eb-8d8c-f1282f01a7a6.png)

![image](https://user-images.githubusercontent.com/5090382/120240148-2a76a680-c260-11eb-9814-5f247a943423.png)

This is my guess how it translates:
- `outside` = intake / incoming
- `supply` = supply 
- `exhaust` = extract
- `outgoing` = exhaust / outgoing

I leave it here for somebody who is also searching for translation between the different terms used.

Personally I'd prefer `outgoing` would be renamed to `extract`, and `outside` to `intake`, even if that is breaking.

**Comment by VincentSC** [comment]
Also put it at https://github.com/coolchip/node-comfoair/issues/11 with more info and edits

**Comment by VincentSC** [comment]
These are the nodes to make the translation for `Temperatures` and `Temperature States`:

```
[{"id":"16d12a73.655df6","type":"switch","z":"fb83beaa.6025","name":"Description","property":"payload.description","propertyType":"msg","rules":[{"t":"eq","v":"Temperature states","vt":"str"},{"t":"eq","v":"Temperatures","vt":"str"},{"t":"else"}],"checkall":"true","repair":false,"outputs":3,"x":810,"y":500,"wires":[["e8254373.6af42"],["e8254373.6af42"],["1223373f.2c45f9"]]},{"id":"1223373f.2c45f9","type":"debug","z":"fb83beaa.6025","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":1210,"y":560,"wires":[]},{"id":"e8254373.6af42","type":"change","z":"fb83beaa.6025","name":"","rules":[{"t":"move","p":"payload.outsideAir","pt":"msg","to":"payload.incomingAir","tot":"msg"},{"t":"move","p":"payload.exhaustAir","pt":"msg","to":"payload.extractAir","tot":"msg"},{"t":"set","p":"payload.extractAir.label","pt":"msg","to":"extract air","tot":"str"},{"t":"set","p":"payload.incomingAir","pt":"msg","to":"incoming air","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":1000,"y":480,"wires":[["1223373f.2c45f9"]]}]
```

Copy it, then import from clipboard, and then connect after the ComfoAir-node.

**Comment by coolchip** [comment]
Added this to the README. Thank you.
