### ISSUE TITLE
Using a ComfoSense in parallel 

### ISSUE THREAD

**Issue by mifrey00** [coolchip/node-red-contrib-comfoair#2]
Thanks for this node.  I successfully ran it on my Zehnder ComfoD 450 (WHR-950).  However, I need to disconnect my ComfoSense control panel to avoid data collisions.  Is there a way to use both the ComfoSense and Node-Red in parallel?

I was thinking to connect the ComfoSense to my Pi on one port (A) using a RS232-USB converter and connect the ventilation unit on another port (B) of the Pi using another RS232-USB converter.  I guess I would need to use a virtual port (C) for Node-Red and redirect both A and C to B?  Is it even possible?

**Comment by coolchip** [comment]
I don't know any way to connect both. You will get many data collisions. This thing is not made for more than one controller.

**Comment by mifrey00** [comment]
I succeeded in connecting both in parallel.  I have the control panel (ComfoSense) connected to ttyUSB0 and the ventilation unit to ttyUSB1 through RS232-USB converters.  They are both configured the same way (stty -F /dev/ttyUSB0 raw 9600 cs8, same for ttyUSB1) and they are both linked together with socat (socat /dev/ttyUSB0 /dev/ttyUSB1) so I can use the control pnael.  The Comfoair node is communicating with a virtual serial port (/home/pi/VMC/ttyV0) that I link to the ventilation unit (socat PTY,link=/home/pi/VMC/ttyV0 /dev/ttyUSB1) only when I want to send a command.  During that time the control panel cannot communicate but that is not a problem it is only for a short time.
