### ISSUE TITLE
setComfortTemperature always results in -20

### ISSUE THREAD

**Issue by t0mkdev** [coolchip/node-red-contrib-comfoair#3]
I've tried:

{
    "name": "setComfortTemperature",
    "params": {
        "temperature": 19
    }
}

and now when I getTemperatures() I get back:

{"value":-20,"label":"comfort","unit":"°C"}

It seems that any value I try results in -20. Do I have to re-wire my CC Ease to fix it now? :)

**Comment by coolchip** [comment]
Uh... that's really to cold for inside. I'll try to fix it.

**Comment by coolchip** [comment]
Give v0.0.4 a try. Should work now.
Please give me a short reply if it's working or not.

**Comment by t0mkdev** [comment]
works fine, thanks!

**Comment by coolchip** [comment]
Thanks for reply.
