### ISSUE TITLE
Invalid checksum or frame length for getTemperatures

### ISSUE THREAD

**Issue by mifrey00** [coolchip/node-red-contrib-comfoair#4]
I often get the error "Invalid checksum or frame length for getTemperatures" in the debug panel.  It occurs maybe once every 3 calls in average.  That might be due to my RS232 line itself but the strange thing is that I am sending a bunch of commands (one after the other) every 15 minutes and the error always happens for the first command which is getTemperatures, which makes me believe that is not due to the RS232 line.

![image](https://user-images.githubusercontent.com/10077480/71627685-3a660300-2bf4-11ea-9b96-067ac534f25d.png)

Also, how can I catch this error to handle it?  I tried the catch node but it does not output anything.

**Comment by coolchip** [comment]
You should be able to catch it with the catch node. 
Please post your flow. So perhaps I can test it on my system. Since now I never seen this error. I only get timeouts. Currently I'm searching for that timeout error.
