### ISSUE TITLE
Setting comfort temperature is broken

### ISSUE THREAD

**Issue by VincentSC** [coolchip/node-red-contrib-comfoair#7]
`{"name":"setComfortTemperature","params":{"temperature":"XX"}}` sets the temperature to random numbers. Even negative numbers.

**Comment by VincentSC** [comment]
When using integers it gives random results. When using a float like XX.Y or XX.YY, it works but wit 20.00 degrees off. So 39.0 results in 19.0, 19.0 results in -1.00.
Expectations: 
- integers converted to floats. The fun of UX: make sure the user can actually be/act stupid. :)
- result not being 20.0 off. This could maybe best be fixed by coolchip?

Checked on the WHR950 in menu P41, ad it's now set 19.0.

**Comment by coolchip** [comment]
Thank you for your help. I will try to fix that soon.

**Comment by VincentSC** [comment]
Was this fixed? If so, here or in the dependency? Still have this to set it to 19:
> {"name":"setComfortTemperature","params":{"temperature":"39.00"}}

**Comment by coolchip** [comment]
Should be fixed in the depenency. Thank you.
