### ISSUE TITLE
SetVentilationLevels documentation

### ISSUE THREAD

**Issue by VincentSC** [coolchip/node-red-contrib-comfoair#9]
For setting the default Ventiation level, use the following command:
```
{
    "name": "setVentilationLevel",
    "params": {
        "exhaustAway": "15",
        "exhaustLow": "35",
        "exhaustMiddle": "50",
        "exhaustHigh": "70",
        "supplyAway": "15",
        "supplyLow": "35",
        "supplyMiddle": "50",
        "supplyHigh": "70"
    }
}
```

(from what I understood, all parameters need to be given)
(I tried to imbalance the numbers to blow out the hot air, but that did not seem to work)

**Comment by coolchip** [comment]
Yes, all parameters must be set. The API of Comfoair wants it so. But I have not tested this function myself.
